image: tetraweb/php

stages:
  - test
  - deploy

before_script:
  - apt-get update
  - apt-get install zip unzip

test:
  stage: test
  script:
  - cd api
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - php composer-setup.php
  - php -r "unlink('composer-setup.php');"
  - php composer.phar update
  - composer install
  - cd Tests
  - phpunit
  - cd ../../ci
  - bash build_zip.sh
  #-  php deploy_release_to_github.php

deploy:
  when: manual
  stage: deploy
  script:
  - ls
  - php -r "echo 'Hello, world!';"