image: composer:composer

before_script:
- bash ci/docker_install.sh > /dev/null

test:app:
  #when: manual
  script:
  -  cd api
  -  composer install
  -  cd Tests
  -  phpunit
  -  cd ../../ci
  -  bash build_zip.sh
  #-  php deploy_release_to_github.php